### ISSUE TITLE
crash in make_mld6v2_msg with mld6v2

### ISSUE THREAD

**Issue by tycho** [troglobit/pim6sd#26] opened 2020-06-15 06:00 UTC
It seems we aren't allocating enough space for the `in6_pktinfo` structure *plus* the `IP6OPT_ROUTER_ALERT`, causing `cmsgp` to be NULL [here](https://github.com/troglobit/pim6sd/blob/master/src/mld6v2.c#L292), causing a NULL pointer dereference and crash [here](https://github.com/troglobit/pim6sd/blob/master/src/mld6v2.c#L302). This fixes the problem for me:

```diff
diff --git a/src/mld6v2.c b/src/mld6v2.c
index 8cd5a4d..6a69593 100644
--- a/src/mld6v2.c
+++ b/src/mld6v2.c
@@ -252,7 +252,7 @@ make_mld6v2_msg(int type, int code, struct sockaddr_in6 *src,
            log_msg(LOG_ERR, 0, "inet6_opt_append(0) failed");
        if ((hbhlen = inet6_opt_finish(NULL, 0, hbhlen)) == -1)
            log_msg(LOG_ERR, 0, "inet6_opt_finish(0) failed");
-       ctllen += CMSG_SPACE(hbhlen);
+       ctllen += CMSG_SPACE(sizeof(struct in6_pktinfo)) + CMSG_SPACE(hbhlen);
 #else                          /* old advanced API */
        hbhlen = inet6_option_space(sizeof(raopt));
        ctllen += hbhlen;
```

**Comment by tycho** [comment] 2020-06-15 06:36
Also, mld6v2 doesn't seem to be working correctly even with that change. It doesn't *crash*, but it does spew this in the logs:

```
warning - sendmsg to ff02::1 with src fe80::a236:9fff:fe51:126e on lan0: Invalid argument
warning - sendmsg to ff02::1 with src fe80::a236:9fff:fe51:126e on lan0.10: Invalid argument
warning - sendmsg to ff02::1 with src fe80::a236:9fff:fe51:126e on lan0.40: Invalid argument
```

I checked where that log's coming from and it's from `send_mld6v2`. It's not clear why it's rejecting it though. For now I'm going to turn off the `mld_version any` directives in my pim6sd.conf file.

**Comment by troglobit** [comment] 2020-06-15 22:13
Awesome patch, thank you for taking the time to look at it!  Now to figure out why `sendmsg()` fails.  I don't have the time right now myself, but I'd start by checking the input arguments.  If they are stack based, make sure they are `memset()` to zero before parts of any struct args are (partially) initialized. If the args are re-used, go back to code path to see if any other function writes to elements we need to clear.  E.g., if buffers are reused from `recvmsg()` or similar.

**Comment by skumardada** [comment] 2020-12-14 04:30
i am still getting the crash in  line 302 in mld6v2  only when i use mld_version 2 . any patch release available ?

**Comment by troglobit** [comment] 2020-12-14 05:28
@skumardada The patch referenced above has not been merged to the master branch yet.  I've waiting for someone to send a pull request, or for me to get some time over to hand-merge it myself.  The downside of the second option is not only my time to do the manual job, I also need to reproduce, test the fix. Since this is not a full-time job that pays the bills for me, I need to prioritize.

**Comment by skumardada** [comment] 2020-12-14 14:42
@troglobit Thanks for the quick reply and i understand  . i will try to create pull request .But i am not quite sure the fix mentioned above fully resolves the issue based on tycho's 2nd comment.  --Thanks

**Closed** 2021-11-17 15:23 UTC

**Comment by troglobit** [comment] 2021-11-17 15:25
Took me a while to get back to this, but I believe I finally found the root cause of this issue.  It wasn't the ctllen patch suggested here, but rather replacing malloc() with calloc() so the CMSG_NXTHDR() macro works as intended.
